### ISSUE TITLE
pb whit ldap : LOG15_ERROR

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/grafana_ynh#18] opened 2019-02-26 22:48 UTC
hi, 
grafana was working very well, but now i have this error : 

  Grafana / Server Error
  Sadly something went wrong
  Failed to sync user
  
  Check the Grafana server logs for the detailed error message.

```
t=2019-02-26T23:38:56+0100 lvl=info msg="LDAP initial bind failed, %v" logger=ldap LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
t=2019-02-26T23:38:56+0100 lvl=eror msg="Failed to sync user" logger=context error="LDAP Result Code 206 \"Empty password not allowed by the client\": ldap: empty password not allowed by the client"
```
no pb with other apps using ldap, 
netdata is ok. 
i tried to remove then reinstall, but i have the same issue.
```
 # yunohost -v
yunohost: 
  repo: stable
  version: 3.4.2.4
yunohost-admin: 
  repo: stable
  version: 3.4.2
moulinette: 
  repo: stable
  version: 3.4.2
ssowat: 
  repo: stable
  version: 3.4.2

# yunohost app info grafana
description: Tableaux de bords de supervision
license: Apache-2.0
name: Grafana
version: 1.2.0~ynh1
```
thx for your help ;)

**Comment by JimboJoe** [comment] 2019-03-02 08:36
Maybe it's related to new version 6.0 that's just got release.
What your grafana version (`dpkg -l |grep grafana`)?

**Comment by isAAAc** [comment] 2019-03-02 15:34
```
ii  grafana                               6.0.0                              amd64        Grafana
ii  grafana-ynh-deps                      1.2.0~ynh1                         all          Fake package for grafana (YunoHost app) dependencies
```

**Comment by JimboJoe** [comment] 2019-03-04 08:22
I've upgrade to grafana 6.0 and didn't reproduce the issue. Can you please possibly share your grafana configuration file?

**Comment by JimboJoe** [comment] 2019-03-04 16:15
I finally got it reproduced.
It seems linked to this upstream [closed bug](https://github.com/grafana/grafana/issues/15245).
Basically, the way to connect to LDAP was supported unintentionally in version 5, and it was removed in version 6.0...
We'll have to find a fix for this new situation :thinking: 
EDIT: Finally, an issue on this was [reopened](https://github.com/grafana/grafana/issues/15643), and hopefully, things may sort them out by themselves :crossed_fingers:

**Comment by isAAAc** [comment] 2019-03-05 09:54
yep , wait && see ;)

thx for your help \o/

<pending>

**Comment by isAAAc** [comment] 2019-03-12 14:08
hi, 
the [reopened ticket](https://github.com/grafana/grafana/issues/15643) is closed, 
do you think we'll have a fix in a few ?

**Comment by JimboJoe** [comment] 2019-03-12 16:06
We have to wait for the [6.0.2 release](https://github.com/grafana/grafana/milestone/123) :wink:

**Comment by JimboJoe** [comment] 2019-03-20 21:52
[6.0.2 version](https://github.com/grafana/grafana/releases/tag/v6.0.2) has been released, and the problem is fixed! :tada:

**Closed as completed by JimboJoe** 2019-03-20 21:52 UTC

**Comment by isAAAc** [comment] 2019-03-25 10:13
i confirm, everything is ok now ;) 
thx @JimboJoe
