### ISSUE TITLE
Service needs to be restart after each reboot

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/grafana_ynh#12] opened 2017-12-13 10:59 UTC
Hi
I get 502 error after each reboot. Restarting the grafana services brings back the grafana interface. Is this issue related to my instance only?

**Comment by JimboJoe** [comment] 2017-12-13 17:19
Can't reproduce your issue with my setup (grafana 4.6.2). What's your version of grafana?

**Comment by anmol26s** [comment] 2017-12-13 18:51
My version is 4.6.2 too

**Comment by JimboJoe** [comment] 2017-12-13 20:59
What does `systemctl|grep grafana-server` says?

**Comment by anmol26s** [comment] 2017-12-13 21:43
```
grafana-server.service                                                                  
 loaded active running   Grafana instance
```

**Comment by JimboJoe** [comment] 2017-12-14 08:44
So the service is enabled and started at system boot.
Any relevant log in `/var/log/grafana/grafana.log`?

**Comment by JimboJoe** [comment] 2018-05-26 07:29
As nothing happened here since a few months, I consider you solved you problem and I close this issue :wink:  
Please feel free to reopen it if there's more to do!

**Closed as completed by JimboJoe** 2018-05-26 07:29 UTC
